version: '3'
services:
  # mysql:
  #   image: mysql:8.0.30
  #   environment:
  #     MYSQL_ROOT_PASSWORD: 123456
  #     MYSQL_DATABASE: test_db
  #     MYSQL_USER: user
  #     MYSQL_PASSWORD: 123456
  #   ports:
  #     - '3306:3306'
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx-config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-config/api_conf.d/:/etc/nginx/api_conf.d/:ro
      - ./nginx-config/api_backends.conf:/etc/nginx/api_backends.conf:ro
      - ./nginx-config/api_gateway.conf:/etc/nginx/api_gateway.conf:ro
      - ./nginx-config/api_json_errors.conf:/etc/nginx/api_json_errors.conf:ro
      - ./nginx-config/api_keys.conf:/etc/nginx/api_keys.conf:ro
    extra_hosts:
      - "${HOST_NAME}:${HOST_GATEWAY}"
    networks:
      - socialnetwork_backend

networks:
  socialnetwork_backend:
    ipam:
      driver: default
      config:
        - subnet: ${HOST_SUBNET}
          gateway: ${HOST_GATEWAY}

# https://datatracker.ietf.org/doc/html/rfc1918
