version: '3'
services:
  mysql:
    image: mysql:8.0.30
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: test_db
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
    ports:
      - '3306:3306'
